spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/squad3}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true